import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/layout/Header";
import Footer from "@/layout/Footer";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Star Wars: Characters",
  description: "Generated by create next app",
  icons: [{ url: "/images/favicon.webp" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
